### ISSUE TITLE
The name list cannot be empty

### ISSUE THREAD

**Issue by islamtashfiq** [fvisin/dataset_loaders#16]
I got the following error in parrallel_loader

site-packages/dataset_loaders-1.0.0-py2.7.egg/dataset_loaders/images/citysca
pes.py", line 188, in __init__
    super(CityscapesDataset, self).__init__(*args, **kwargs)
  /python2.7/site-packages/dataset_loaders-1.0.0-py2.7.egg/dataset_loaders/parallel_loade
r.py", line 356, in __init__
    raise RuntimeError('The name list cannot be empty')
RuntimeError: The name list cannot be empty

**Comment by fvisin** [comment]
Is it possible that the dataset is not in the location you specified in the
config file?

Il 01 ago 2017 1:19 PM, "islamtashfiq" <notifications@github.com> ha
scritto:

**Comment by islamtashfiq** [comment]
You were right. I wanted to use this dataset https://download.visinf.tu-darmstadt.de/data/from_games/ instead of cityscapes, but it didn't work. How can I train using the dataset, it has the same format as cityscapes. What I am asking is that possibly I should make minor changes to the cityscapes.py, but I don't know where.

**Comment by islamtashfiq** [comment]
Also it seems that training is done on cpu even though I used argv += ['--devices', '/gpu:0'].

**Comment by fvisin** [comment]
I am sorry I cannot provide support on new datasets (and the support I can
generally provide is limited anyway!).

Regarding the device flag (although it's not really a dataset leader issue)
you can check the device_list (?, I don't recall the exact name) variable
putting a breakpoint in the main loop. I'm sorry I cannot assist you more
than this.

Il 01 ago 2017 4:41 PM, "islamtashfiq" <notifications@github.com> ha
scritto:

**Comment by islamtashfiq** [comment]
Thanks for your help.
