### ISSUE TITLE
get_n_classes(), get_void_labels are not found

### ISSUE THREAD

**Issue by ChidanandKumarKS** [fvisin/dataset_loaders#17]
get_n_classes(), get_void_labels are not found. Kindly suggest

**Comment by fvisin** [comment]
Hi, I confirm those methods are not there as this is python, not Java: you can easily access those information via the attributes of the object as follows:

```python
In [1]: from dataset_loaders import CamvidDataset

In [2]: dd = CamvidDataset()

In [3]: dd.nclasses
Out[3]: 12

In [4]: dd.void_labels
Out[4]: [11]
```

**Comment by ChidanandKumarKS** [comment]
Thanks for your kind reply

**Comment by ChidanandKumarKS** [comment]
Dear Francesco,

Thanks for your  previous reply.

Moving further i had new issue below. i had below issue

I have given appropriate datasets along with proper folder and train and
annotation datasets properly. The inference function test.py at line 63 is
crashing

Below error crashes
X, Y = iterator.next()
ValueError: too many values to unpack.

Any solutions to the above problem would be really helpful. Kindly do the
needful

Thanks
Kumar

**Comment by ChidanandKumarKS** [comment]
Dear Francesco,

Thanks for your  previous reply.

Moving further i had new issue below. i had below issue

I have given appropriate datasets along with proper folder and train and
annotation datasets properly. The inference function test.py at line 63 is
crashing

Below error crashes
X, Y = iterator.next()
ValueError: too many values to unpack.

Any solutions to the above problem would be really helpful. Kindly do the
needful

Thanks
Kumar

**Comment by fvisin** [comment]
The error depends on iterator.next() returning more than 2 values (i.e., more than the X, Y variables that it's trying to fill). The tests are probably outdated (and are not proper tests either to be honest), so I wouldn't count on them to check if the dataset is loaded properly. I'd rather suggest you to run your code interactively (i.e., ipython) to inspect what is returned by the dataset.

I am sorry I cannot help you more on this, but the support we provide on this framework has to be limited to allow us to continue with our other projects. If you find out that the test is broken, a PR to fix it is more than welcome!
